# Learnings related to PyTorch

In [3]:
import torch 
import torch.nn as nn
import pandas as pd
import numpy as np
import torch.nn.functional as F

### Coversion to one-Hot using 
 - Torch: `nn.functional.one_hot`
 - Pandas: `.get_dummies()`

In [4]:
y = 1
num_classes = 3
data_ = pd.DataFrame({
    'y':[1,3,4,2,3,1,4,2,3,4,1]
})

# Create the one-hot encoded vector using NumPy
one_hot_numpy = np.array([0, 1, 0])

# Create the one-hot encoded vector using PyTorch
one_hot_pytorch = F.one_hot(torch.tensor(y),num_classes=3)
#print(one_hot_numpy)
#print(one_hot_pytorch)

print("Torch OneHot",F.one_hot(torch.tensor(data_['y'])))

print("Numpy One-Hot Cnverted ",torch.tensor(pd.get_dummies(data_['y']).to_numpy().astype(int)))

Torch OneHot tensor([[0, 1, 0, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1],
        [0, 1, 0, 0, 0]])
Numpy One-Hot Cnverted  tensor([[1, 0, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [1, 0, 0, 0],
        [0, 0, 0, 1],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1],
        [1, 0, 0, 0]], dtype=torch.int32)


In [5]:
criterion = nn.CrossEntropyLoss()

### Cross Entropy

In [6]:
print(criterion)

CrossEntropyLoss()


In [7]:


y = [2]
scores = torch.tensor([[0.1, 6.0, -2.0, 3.2]])

# Create a one-hot encoded vector of the label y
one_hot_label = F.one_hot(torch.tensor(y), scores.shape[1])

# Create the cross entropy loss function : As object of the CrossEntropyLoss class
criterion = nn.CrossEntropyLoss()  

# Calculate the cross entropy loss
loss = criterion(scores.double(),one_hot_label.double())    
print(loss)

tensor(8.0619, dtype=torch.float64)


The method in the nn.CrossEntropyLoss class that is being called is forward(). When you call criterion(scores.double(), one_hot_label.double()), it is equivalent to calling criterion.forward(scores.double(), one_hot_label.double()). The forward() method performs the actual computation of the loss.

In [8]:
# Using the functinal nn.functional.cross_entropy function
F.cross_entropy(scores.double(),one_hot_label.double())

tensor(8.0619, dtype=torch.float64)

### Sample MSE using pyTorch and Numpy

In [10]:

y_hat = np.array(10)  # 10 outputs
y = np.array(1)       

print("y_hat",y_hat)
print("y",y)

# Calculate the MSELoss using NumPy
mse_numpy = np.mean((y.astype(float)-y_hat.astype(float))**2)



# Create the MSELoss function
criterion =  nn.MSELoss()

# Calculate the MSELoss using the created loss function
mse_pytorch = criterion(torch.tensor(y_hat).float(), torch.tensor(y).float())


print("mse_numpy",mse_numpy)
print("mse_pytorch",mse_pytorch)

y_hat 10
y 1
mse_numpy 81.0
mse_pytorch tensor(81.)


## Sample Neural Nework : Regression
```python
# Number of epochs to train
for n in range(num_epochs):
  for data in dataloader:
    # Reset gradients to zero
    optimizer.zero_grad()
    feature, target = data
    prediction = model(feature)    
    loss = criterion(prediction, target)   # MSE for regression, CrossEntropy for classification etc   
    #Compute the gradients of parameters (weights, bias)
    loss.backward()         
    # Update the weigths and bias -> W = W - dloss/dW , B = B - dloss/dB
    optimizer.step()

# Show the model weights and bias ( parameters)

## A View of the internal weights and Bias.
`Counting Learnable parameters`

In [34]:
x = torch.tensor([[1,2,3,4,5,6,7,8],[1,3,5,7,2,4,6,8]])  # 2 inputs, 8 features

In [35]:
x.size()

torch.Size([2, 8])

In [36]:
model = nn.Sequential(nn.Linear(8,4), nn.Linear(4,2)) # Hidden 1 : 4 layers, Hidden 2 : 2 layers


In [37]:
model(x.float())


tensor([[ 0.5136,  0.0814],
        [ 0.8048, -0.3666]], grad_fn=<AddmmBackward0>)

In [38]:
model.children

<bound method Module.children of Sequential(
  (0): Linear(in_features=8, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=2, bias=True)
)>

In [76]:
count_weight = 0
count_bias = 0

for i,param in enumerate(model.children()):  # or param in model.parameters()
    print(f"Weights {i}: ", param.weight)
    print(f"Bias {i}:", param.bias)
    print()
    i += 1
    count_weight += count_weight + param.weight.numel()
    count_bias += count_bias + param.bias.numel()

print("Number of weight params",count_weight)
print("Number of bias params",count_bias)
print("Number of learnable parameters",count_weight + count_bias)

Weights 0:  Parameter containing:
tensor([[-0.2021, -0.2454,  0.0112,  0.0805,  0.2412,  0.1939, -0.2667,  0.0729],
        [ 0.2147, -0.3125, -0.1370,  0.0931,  0.3466, -0.3268,  0.3312, -0.2827],
        [-0.1324,  0.1452,  0.0364, -0.2102,  0.1515, -0.3330,  0.3410, -0.0280],
        [ 0.3400,  0.0100, -0.1442, -0.2333,  0.2605, -0.1619,  0.1231, -0.0291]],
       requires_grad=True)
Bias 0: Parameter containing:
tensor([-0.0342, -0.0171, -0.3411,  0.2428], requires_grad=True)

Weights 1:  Parameter containing:
tensor([[ 0.3980, -0.4980,  0.1079, -0.1080],
        [-0.2084,  0.2341, -0.0214,  0.2514]], requires_grad=True)
Bias 1: Parameter containing:
tensor([-0.0673,  0.3301], requires_grad=True)

Number of weight params 72
Number of bias params 10
Number of learnable parameters 82


In [82]:
for name,param in model.named_parameters():  # or param in model.parameters()
    print(name, param)

0.weight Parameter containing:
tensor([[-0.2021, -0.2454,  0.0112,  0.0805,  0.2412,  0.1939, -0.2667,  0.0729],
        [ 0.2147, -0.3125, -0.1370,  0.0931,  0.3466, -0.3268,  0.3312, -0.2827],
        [-0.1324,  0.1452,  0.0364, -0.2102,  0.1515, -0.3330,  0.3410, -0.0280],
        [ 0.3400,  0.0100, -0.1442, -0.2333,  0.2605, -0.1619,  0.1231, -0.0291]],
       requires_grad=True)
0.bias Parameter containing:
tensor([-0.0342, -0.0171, -0.3411,  0.2428], requires_grad=True)
1.weight Parameter containing:
tensor([[ 0.3980, -0.4980,  0.1079, -0.1080],
        [-0.2084,  0.2341, -0.0214,  0.2514]], requires_grad=True)
1.bias Parameter containing:
tensor([-0.0673,  0.3301], requires_grad=True)


### Loading Data from datasets

```python
# Create a dataset from the two generated tensors
from torch.utils.data import  TensorDataset, DataLoader
dataset = TensorDataset(features, target)
batch_size=64
# Create a dataloader using the above dataset
dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)



## Evaluation

```python
model.eval()
validation_loss = 0.0
validation_dataloader = # Some dataset portion

for epoch in range(num_epochs):
    with torch.no_grad():
        for data in validation_dataloader:
            features , target = data
            prediction = model(features)
            loss = criterion(prediction, target)
            validation_loss += loss.item()
    validation_loss_epoch = validation_loss / len(dataloader)    
```
## Accuracy
```python
from torchmetrics import Accuracy
metric = Accuracy(task="multiclass", num_classes=num_classes)
for epoch in range(num_epochs):
    with torch.no_grad():
        for data in dataloader:
            features, target = data
            outputs = model(features)
            acc = metric(outputs.softmax(dim=-1), target.argmax(dim=-1))  # If the target is OneHot represented [0,1,0]
    # Calculate accuracy over the whole epoch
    acc = metric.compute()
    print("Accuracy in Epoch:{epoch}",acc)
    acc = metric.reset()
```

